# Generated by Django 6.0 on 2025-12-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='temprature',
            field=models.FloatField(),
        ),
    ]
